### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by LamaarK** [WEEZOOKARP/mint-houseRobbery#1]
**One houserobbery location?**
Okay, so this only has one location set up, can this not be multiple locations?

**Feature Id like to see**
I think the community would like to see many more locations to rob and not just homes, lets look at business' or offices

**Comment by WEEZOOKARP** [comment]
Server owners can add their own custom robberies with locations and loot spots

`Config.Locations = {
    {
        name = "Wild Oats Drive",
        canrob = true, -- do not change this
        location = vector3(-174.07, 502.62, 137.42),
        inside = vector3(-173.72, 495.69, 137.57),
        exit = vector3(-174.34, 497.89, 137.67),
        outside = vector3(-177.07, 503.4, 137.03),
        loot = {
            vector3(-166.92, 495.6, 137.65),
            vector3(-165.97, 482.16, 137.27),
            vector3(-167.31, 487.45, 133.84),
            vector3(-174.65, 492.51 ,130.04),
        }
    }, -- copy from the line below til the bracket with a comma and then paste below it to add more locations
    {
        name = "Tinsel Towers",
        canrob = true, -- do not change this
        location = vector3(-614.64, 46.96, 43.70),
        inside = vector3(-596.34, 59.45, 108.03),
        exit = vector3(-596.38, 56.47, 108.03),
        outside = vector3(-615.12, 42.58, 43.59),
        loot = {
            vector3(-605.21, 55.93, 108.04),
            vector3(-610.6, 52.52, 106.62),
            vector3(-617.01, 56.08, 101.83),
            vector3(-609.27, 58.22, 101.82),
        }
    },

}`
